### PR TITLE
Changed persistent to false and changed the colors as required

### LINKED ISSUE #511: [Feature]: Update colors in `StatsScoringDialog.vue` to leverage themes' chocolate and cream colors
### Feature Summary

The `StatsScoringDialog` is used to explain how the ranking system works. It has a section showcasing the point chips that players earn based on their weekly ranked performance that uses a white background. This would look more consistent with the overall look and feel if the background were made cream and the text color were chocolate.

### Detailed Description

Specifically it's this section of the `StatsScoringDialog`:

image

Currently the background is white and the text is black. It would look better if this was a cream background (surface-2) and the text were chocolate (surface-1). 

Additionally we should set `:persistent="false"` on the `StatsScoringDialog`'s instance of the `BaseDialog` so that it closes when you click outside the dialog, given that this is an informational dialog that doesn't require you to make a decision.

### PR DESCRIPTION
**Pull request by karan3267**
changed the background colour and text colour

## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #511

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [x] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

changed persistent to false on baseDialogue.vue
added bg color and text color for the dialogue box as per the requirments

### CODE REVIEW

**Review by seriouslysean — APPROVED** [review]
Code looks ok to me, leaving final approval to @itsalaidbacklife.

Thanks for the contribution!

**Review by itsalaidbacklife — CHANGES_REQUESTED** [review]
Thanks for your contribution! This is the right general idea. It needs a few changes (see the comments) to be ready for deployment. 

Two other general notes:
1) I've added the issue number #511 that this addresses to the PR description. This helps us understand what the PR is about and track when issues are completed. Please include the issue number in future pr's

2) Please run `npm run version: patch` to bump the package version a patch number. This helps us keep track of what version of the app is currently deployed

**Comment by itsalaidbacklife** [comment]
Thanks again @karan3267 for your contribution! If you have any questions about the pr feedback, please feel free to ask them in the PR comments. Or if you'd prefer real time support, you can join our [discord](https://discord.gg/6vQCFa6nvP) to chat with myself and the other devs synchronously

**Comment by itsalaidbacklife** [comment]
@karan3267 are you still interested in completing this issue? Overall it is close, but the PR feedback will need to be addressed for this to be merged

**Comment by karan3267** [comment]
yes i would like complete this issue and close it.

**Comment by karan3267** [comment]
i have made the changes in StatsScoringDialog.vue please review them and if everything is good merge it to main branch

**Review by itsalaidbacklife — APPROVED** [review]
Nice work. As a final step, please run `npm run version: patch` one time and push the result (this will commit a change that updates the version field in the package files). 

Thanks for your contribution!

**Comment by karan3267** [comment]
I had run npm run version: patch and pushed the changes . Sorry for the delay on the project.
Thank you!

**Review by itsalaidbacklife — APPROVED** [review]
Nicely done. Thanks for your contribution! If you'd like to make another contribution, feel free to pick up any issue that interests you. Or if you'd like help finding something to work on, you can use the #code channel of our [discord](https://discord.gg/6vQCFa6nvP) to chat with myself and the other devs about it

**Pull request merged**
