### PR TITLE
[Bug]: Replace public/img/logo-dead.svg #1099

### LINKED ISSUE #1099: [Bug]: Replace public/img/logo-dead.svg
### Bug Summary

One of the logo images (logo-dead.svg) should be replaced with an updated version.

### Detailed Description

We should replace `public/img/logo-dead.svg` with this file in order to fix a visual issue with the previous version of the file where the opacity was incorrect on one of the eyes. We should use this version instead:

logo-dead

### PR DESCRIPTION
**Pull request by matinshaikh31**
## Issue number

Relevant [#1099 ](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #1099

## Please check the following

- [X ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [X] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [X] Have tests been added to cover any new features or fixes?
  - [X] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
replace public/img/logo-dead.svg with the new file in order to fix a visual issue with the previous version of the file where the opacity was incorrect on one of the eyes

### CODE REVIEW

**Review by itsalaidbacklife — COMMENTED** [review]
This is exactly what was requested, but in reviewing it I see that the file size has changed, which is an unintended regression.

If you are comfortable using figma or any design software, could you upload the image and adjust it to have the original size of 293x255px so that it only includes the content without the surrounding whitespace?

If not I will follow up with our graphic designer to provide an updated image to use. Thank you for your help and your patience

**Comment by matinshaikh31** [comment]
i have resize the svg

**Comment by itsalaidbacklife** [comment]
This is close but if you look at the diff, the new image still has whitespace around it so the actual content has changed size. I will investigate it when I next get to a computer

**Comment by matinshaikh31** [comment]
can you share the image that you want to update in the website

**Comment by itsalaidbacklife** [comment]
@matinshaikh31 here is an updated image:
logo-dead

**Review by itsalaidbacklife — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
