### PR TITLE
Display players lost to in Stats Leaderboard

### PR DESCRIPTION
**Pull request by gVirtu**
## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [x] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
As requested in #182 , this adapts the "Players Beaten" dialog to include a list of **Losses** in addition to the list of **Wins**.

In the "Total" column, a counter is also shown next to the player's name, depicting the number of times each player appeared in winning/losing matches over the weeks.

Screenshot from 2022-10-28 23-53-11

All feedback is appreciated! :)

### CODE REVIEW

**Review by itsalaidbacklife — CHANGES_REQUESTED** [review]
This is excellent. The implementation looks just right. The only changes I'm requesting pertain to testing. The menu that now has both players beaten and lost to currently has a selector on the entire menu used during testing to identify the players beaten. 

Now that selector should be moved into the specific list inside the menu for players beaten, and a complementary selector for the players lost to should be added to the corresponding list. Then we can add an assertion to one of the Stats tests to add an assertion about the players lost to

**Comment by itsalaidbacklife** [comment]
Please don't hesitate to ask any questions you might have here, or if you'd like to chat in real-time (about the code, the game, or anything else), you can join us on [discord](https://discord.gg/6vQCFa6nvP)

Thanks so much for your help! We just wrapped up our 3rd season championship last night and have kicked off the new competitive season, so this is a timely QoL change :)

**Comment by gVirtu** [comment]
@itsalaidbacklife thank you for the kind words and thorough feedback!! :smile: 

I've updated the selectors and the tests (I left one for the outer v-card since it makes it easier to get to the intended close button), and also made sure to include the special case for the Total column.

Really excited about the thriving competitive scene! I haven't delved too deep into strategic play just yet, though played a few matches against AI and liked what I saw quite a bit, as a fellow digital card game enjoyer. :)

Thanks for the discord invite as well! Hopped aboard and will check it out.

**Review by itsalaidbacklife — APPROVED** [review]
*Chef's kiss*

**Comment by itsalaidbacklife** [comment]
Resolves #182

**Pull request merged**
