### PR TITLE
Bug #753 May counter dialog

### LINKED ISSUE #753: [Bug]: Drawing extra card during resolve/counter phase
### Bug Summary

Being able to draw a card while the opponent decides whether to counter or resolve your one-off

### Detailed Description

After you've played a one-off, when the opponent is deciding if he's going to counter it, the game lets you draw a card even though you shouldn't be able to.
It works with all one-offs. When it's a 4 it also works while the opponent is choosing his discards, and a very similar thing happens with the 3 when he's choosing the card he's going to recover.

Quick example:

Playing a 6 as a one-off

imagen

Clicking anywhere in the highlighted area makes the "Opponent may counter" label go away, as if it was your turn again

imagen

imagen

And the game lets you draw

imagen

All of this while the opponent hasn't decided yet

imagen

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by Haviles04**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #753 

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

- Added persistent prop so clicking outside dialog will not close it
- Added error handling inside `draw.js` api endpoint

### CODE REVIEW

**Review by itsalaidbacklife — COMMENTED** [review]
This looks great. @Haviles04 could you add a test case where we set up this situation and then hook into the `gameStore`  using the window in order to directly request to draw a card as the player while ignoring the overlay in order to assert that the snackbar appears?

**Comment by Haviles04** [comment]
> This looks great. @Haviles04 could you add a test case where we set up this situation and then hook into the `gameStore`  using the window in order to directly request to draw a card as the player while ignoring the overlay in order to assert that the snackbar appears?

Absolutely can, should I add it to the current test that checks for the opponent may counter overlay, or should I make a new test

**Comment by itsalaidbacklife** [comment]
> > This looks great. @Haviles04 could you add a test case where we set up this situation and then hook into the `gameStore`  using the window in order to directly request to draw a card as the player while ignoring the overlay in order to assert that the snackbar appears?
> 
> Absolutely can, should I add it to the current test that checks for the opponent may counter overlay, or should I make a new test

Let's add it to the existing test since it's already about the same situation

**Review by itsalaidbacklife — APPROVED** [review]
Great work

**Pull request merged**
