### PR TITLE
Added where condition to get-seasons-without-rankings.js so seasons that haven't started yet aren't shown to Fix issue #163

### PR DESCRIPTION
**Pull request by P-DR0ZD**
## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [x] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

Added where condition so the user can't see seasons that haven't started yet from issue #163

### CODE REVIEW

**Comment by itsalaidbacklife** [comment]
Looks good! Let's update the tests to check that this works as well. Can you update tests/e2e/fixtures/statsFixture.js to add an additional season that has a start time in the future (using dayjs to dynamically set the start time to the future)

**Comment by P-DR0ZD** [comment]
I added the test you were suggesting I also added a test inside of stats.spec.js to check if the future date isn't being shown and changed one of the tests in stats.spec.js because it was falling because it's start date was a date in the future.

**Comment by itsalaidbacklife** [comment]
@P-DR0ZD Looks like there is a failing test case in the stats file: `1) Selects different seasons to show their results`. This is likely due the changes, so it will warrant fixing. We can discuss here or on discord if it gives you trouble. Are you able to replicate the failure locally?

I'll add that there were additional tests failing in `reconnecting.spec.js` but that they are unrelated to your PR. I am fixing the reconnecting tests in #211 so updating from main should resolve that problem, though we still need to sort out the stats page test.

**Comment by P-DR0ZD** [comment]
Yea I should be able to fix that later today

**Comment by P-DR0ZD** [comment]
I think this fixed the issue. At least it did on my end

**Comment by itsalaidbacklife** [comment]
Resolves #163

**Review by itsalaidbacklife — APPROVED** [review]
Looks good! Thanks for the contribution. This will save me time

**Pull request merged**
