### PR TITLE
Remove white space from username

### PR DESCRIPTION
**Pull request by mud1tx**
## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

In this issue, we have to remove the white space from the username. I run the project on localhost and test all the cases.

issue:   #362 

 

https://user-images.githubusercontent.com/89539376/232382697-fb69ba72-4dda-4d0f-92f9-62e4e27ba2bb.mp4

### CODE REVIEW

**Comment by mud1tx** [comment]
@itsalaidbacklife Do I have to create a new PR for that?

**Comment by itsalaidbacklife** [comment]
No you can just update package.json in the same branch you have here and push

**Comment by mud1tx** [comment]
> This looks great. Could you please update the `version` field in `package.json` a patch version to 4.3.11? Thanks for your contribution!
Done

**Review by itsalaidbacklife — APPROVED** [review]
Looks good; nice work

**Pull request merged**
