### PR TITLE
Feature/adds win rate on player menu stats

### LINKED ISSUE #201: [Feature]: Update Stats leaderboard menu to include win rate
### Feature Summary

When you click a cell in the StatsLeaderboard, you see a menu with all the players who won and lost agains the selected player in the selected week. We should update this menu to additionally include the win rate at the bottom of that menu

### Detailed Description

Here is the menu in question:
0DE86CA5-D993-44D8-A3F7-8FE09F24B277

We should include a third section, “Win Rate” below “Wins” and “Losses”, at the bottom of this menu. Which displays the % of completed matches in the relevant week (or total for the total column) that the selected player won.

The relevant file is `client/js/components/StatsLeaderboardCell.vue` 

In addition, the header on this menu should be adjusted to specify which player’s results we are viewing for which week. So instead of simply saying “Results”, the header should read “[username] Week [week_number] Results” e.g. “aleph_one Week 3 Results”. When viewing a menu for the total column, it should use the season name instead e.g. “ aleph_one Spades 2022 Results”

### PR DESCRIPTION
**Pull request by franciscoemanuel**
## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [x] Has the documentation been updated accordingly?
 
## Please describe additional details for testing this change
Resolves #201 

- Adds win rate section on player stats menu
- Renames stats menu title to  “[username] Week [week_number] Results”

image

### CODE REVIEW

**Comment by franciscoemanuel** [comment]
@itsalaidbacklife

**Review by itsalaidbacklife — CHANGES_REQUESTED** [review]
Excellent work. I committed one additional change to filter incomplete matches out of the count, but otherwise this is exactly right in terms of application and test code. I can't easily run the linter on your pr, so could you please run `npm run lint:fix` and commit + push the changes so we pass CI? We also just merged another PR into main, so if possible could you merge `main` into your fork and additionally update the `package.json` version to 3.2.4? With those three changes (lint, merge main into fork, and bump package version), we will be good to merge.

Thanks for your help! We really appreciate your contribution. It will go live in production in a few minutes after merge. It's an exciting QoL improvement for the players, and we just started at the 4th and final competitive season of our first year of ranked play, so this is very timely. 

If you have any questions please feel free to ask here. And if you're at all interested in chatting in real time about this issue or any others, or to find an opponent to play the game, please feel free to join [our discord](https://discord.gg/6vQCFa6nvP).

**Comment by franciscoemanuel** [comment]
@itsalaidbacklife done!

**Review by itsalaidbacklife — APPROVED** [review]
Great work; thanks for your help! If you'd be interested in contributing further, of course we'll welcome your help! Please feel free to grab any issue that appeals to you. And if you'd like, we'd be delighted to chat about your experience and interests with an eye towards how me might help you find contributions that are rewarding to you in terms of technical practice, user experience improvements, or anything else!

Regardless, thanks again for your help, great work, and happy hacktoberfest!

**Pull request merged**
