### PR TITLE
541 undefined username

### LINKED ISSUE #541: [Bug]: hasValidUsername policy errors when `req.body.username` is null.
### Bug Summary

The `hasValidUsername` policy is intended to validate whether requests that require the client to send a `username` in the request body do so (rejecting the requests otherwise). It has a type safety issue where if the `username` is missing from the request body, it actually errors and sends a 500 response, rather than correctly returning a ` badRequest()` 400 response.

### Detailed Description

Here is the policy:

```
module.exports = function (req, res, next) {
  const username = req.body.username.trim(); // this errors if req.body.username is undefined (can't .trim() undefined)

  if (!username) {
    return res.badRequest({ message: 'Please provide a non-empty username' });
  }

  if (typeof username !== 'string' || !username.match(/^[\w.@-]+$/)) {
    return res.badRequest({ message: 'Your username must contain only letters or numbers' });
  }
  req.body.username = username;
  return next();
};
```

We can fix this with optional chaining in the first line of the policy function
```
const username = req.body.username?.trim();
```

### Current Behavior

Sending a request to signup without a username causes the backend to send a 500 response.

### Expected Behavior

Sending a request to signup with no username causes the backend to send a 400 response.

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by ABertaud**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #541 

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

### CODE REVIEW

**Review by seriouslysean — APPROVED** [review]
Good defensive add, leaving final approval to @itsalaidbacklife. 👍 

Thanks for the contribution!

**Review by itsalaidbacklife — APPROVED** [review]
This looks great, thank you. Normally we bump the version in package.json rather than package-lock.json. Can you bump us there from 5.0.0 to 5.0.1? 

package-lock.json should either be left alone or updated to 5.0.1 to match package.json

**Comment by seriouslysean** [comment]
@itsalaidbacklife I'll complain about this forever, but we should be using npm version which will bump both package files and tag the build on merge. Package lock is meant to be a locked version of the package file. https://docs.npmjs.com/cli/v9/commands/npm-version

Maybe we can document it better and add npm bump scripts to avoid the tag if you prefer.

**Comment by ABertaud** [comment]
Alright, I used `npm version <new_version>` which updated both `package.json` and `package-lock.json`.

**Review by itsalaidbacklife — APPROVED** [review]
Nicely done

**Pull request merged**
