### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by AntonBeYt**
Removed sentence about setting up from paragraph about goal.

### CODE REVIEW

**Review by itsalaidbacklife — COMMENTED** [review]
Good catch. The same mistake exists in the es.json and fr.json files as well. Please fix them there as well so that Spanish and French speaking users have the same experience, and then this is good to merge

**Comment by AntonBeYt** [comment]
I don't really understand Spanish or French but hopefully I understood enough to remove the correct sentences

**Review by itsalaidbacklife — COMMENTED** [review]
Close, but you removed one to many sentences from the es and fr files. The part to remove is what is duplicated in the next section

**Review by itsalaidbacklife — APPROVED** [review]
Good catch. Thank you for your contribution!

**Pull request merged**
