### PR TITLE
Configure ESLint to enforce consistent spacing in Comments

### LINKED ISSUE #1050: [DevEx]: Configure eslint rule to require space in front of comments
### Improvement Summary

To standardize comment formats, we should configure the [spaced-comment](https://eslint.org/docs/latest/rules/spaced-comment) estlint rule to require a whitespace in the beginning of each comment

### Detailed Description

We should then run `npm run lint:fix` to automatically fix all violations across the project.

### PR DESCRIPTION
**Pull request by Mang0codes**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #1050

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
Run `npm run lint:fix` to automatically fix all violations across the project.

### CODE REVIEW

**Review by itsalaidbacklife — APPROVED** [review]
Nicely done

**Comment by itsalaidbacklife** [comment]
Just need to fix `api/helpers/gamestate/moves/resolve/two.js` which has a comment that violates the rule and this should be good

**Comment by Mang0codes** [comment]
> Just need to fix `api/helpers/gamestate/moves/resolve/two.js` which has a comment that violates the rule and this should be good

Hi thats because someone commited changes to that file after I raised this PR . Running npm run lint:fix will fix it thank you

**Comment by itsalaidbacklife** [comment]
> > Just need to fix `api/helpers/gamestate/moves/resolve/two.js` which has a comment that violates the rule and this should be good
> 
> 
> 
> Hi thats because someone commited changes to that file after I raised this PR . Running npm run lint:fix will fix it thank you  

Correct but we can't merge until that is corrected in this PR or this and all other prs will fail CI. If you can lint your branch today I will merge this first, to prevent further merge conflicts

**Comment by Mang0codes** [comment]
> > > Just need to fix `api/helpers/gamestate/moves/resolve/two.js` which has a comment that violates the rule and this should be good
> > 
> > 
> > Hi thats because someone commited changes to that file after I raised this PR . Running npm run lint:fix will fix it thank you
> 
> Correct but we can't merge until that is corrected in this PR or this and all other prs will fail CI. If you can lint your branch today I will merge this first, to prevent further merge conflicts

I have already created a pull request please review it

**Pull request merged**
